spring:
  datasource:
    # DBの内容をローカルに保存する
    url: jdbc:h2:./testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      # @Entityのテーブルがない場合削除する
      # アプリケーションが終了してもテーブルを削除しない
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
  file:
    path: ./log